import {createRequire}from'node:module';
import {webcrypto,createHash,randomUUID}from'node:crypto';
import assert from'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_NODE_MODULES?process.env.CODEX_NODE_MODULES+'/playwright':'playwright');
const APP='http://127.0.0.1:8899',MOCK='http://127.0.0.1:8877';
const b=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM});let external=0;
const makeState=note=>({events:[{id:'e',company:'격리 동기화',role:'검수',tier:'A',date:'2026-10-01',time:'',stage:'apply',kind:'deadline',result:'',hold:false,note,url:''}],axes:{},inbox:[],dismissed:[],archived:{},qualifications:[],outProposals:[],ignoredOut:{},radarSeen:{},radarIdentity:{},seedVersion:2,resultVersion:1,updatedAt:1,profile:{done:true,pdb:false,name:'격리',jobs:[],axisOrder:[],criteria:{},excludeCompanies:[],excludeRoles:[],strength:'',want:'',avoid:'',prompt:'',createdAt:1}});
async function device(initial){const c=await b.newContext({serviceWorkers:'block'});await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='cdn.jsdelivr.net')return r.fulfill({status:200,contentType:'text/css',body:''});if(u.hostname!=='127.0.0.1'||!['8877','8878','8899'].includes(u.port)){external++;return r.abort('blockedbyclient');}if(u.port==='8878')return r.fulfill({status:200,contentType:'application/json',body:'[]'});return r.continue();});await c.addInitScript(s=>localStorage.setItem('jobRadarStateV3',JSON.stringify(s)),initial);const p=await c.newPage();p.setDefaultTimeout(12000);await p.goto(APP,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>!!window.__dbg);return{c,p};}
async function connect(p,room){await p.evaluate(room=>{document.getElementById('sRoom').value=room;document.getElementById('syncSave').click();},room);await p.waitForFunction(()=>window.__dbg.cfg()?.baseRev>0&&!window.__dbg.cfg()?.dirty);await p.waitForTimeout(900);}
async function row(room){const id=createHash('sha256').update('chwijun-radar-room:'+room).digest('hex'),rows=await(await fetch(MOCK+'/rest/v1/rpc/radar_get',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({p_id:id})})).json();if(!rows.length)return null;const[,iv,ct]=rows[0].payload.split('.'),raw=await webcrypto.subtle.importKey('raw',new TextEncoder().encode(room),'PBKDF2',false,['deriveKey']),key=await webcrypto.subtle.deriveKey({name:'PBKDF2',salt:new TextEncoder().encode('chwijun-radar-sync-v1'),iterations:180000,hash:'SHA-256'},raw,{name:'AES-GCM',length:256},false,['decrypt']),plain=await webcrypto.subtle.decrypt({name:'AES-GCM',iv:Buffer.from(iv,'base64url')},key,Buffer.from(ct,'base64url'));return{revision:rows[0].revision,state:JSON.parse(new TextDecoder().decode(plain))};}
const result={};
try{
 {const room='persist-'+randomUUID(),{c,p}=await device(makeState('OLD'));await connect(p,room);await p.evaluate(()=>{window.__oldSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='jobRadarStateV3')throw new DOMException('quota','QuotaExceededError');return window.__oldSetItem.call(this,k,v);};window.__dbg.state().events[0].note='UNSAVED';window.__dbg.save();});await p.waitForTimeout(1600);const local=await p.evaluate(()=>({disk:JSON.parse(localStorage.getItem('jobRadarStateV3')).events[0].note,memory:window.__dbg.state().events[0].note,cfg:window.__dbg.cfg(),saveError:!document.getElementById('saveErr').hidden})),remote=await row(room);assert.equal(local.disk,'OLD');assert.equal(local.memory,'UNSAVED');assert.equal(local.cfg.baseRev,1);assert.equal(local.cfg.dirty,false);assert.equal(local.saveError,true);assert.equal(remote.state.events[0].note,'OLD');await p.evaluate(()=>Storage.prototype.setItem=window.__oldSetItem);await p.reload({waitUntil:'domcontentloaded'});await p.waitForTimeout(800);assert.equal(await p.evaluate(()=>window.__dbg.state().events[0].note),'OLD');result.failedLocalSaveNeverUploads=true;await c.close();}
 {const room='large-'+randomUUID(),{c,p}=await device(makeState('A'.repeat(300000)));await connect(p,room);const remote=await row(room);assert.equal(remote.state.events[0].note.length,300000);assert.equal(await p.evaluate(()=>window.__dbg.syncIssue()),null);result.largeEncryptedState=true;await c.close();}
 {const a='room-a-'+randomUUID(),z='room-z-'+randomUUID(),{c,p}=await device(makeState('A'));await connect(p,a);await fetch(MOCK+'/__delay?ms=1500');await p.evaluate(()=>{window.__dbg.state().events[0].note='NEW_ROOM';window.__dbg.save();});await p.waitForTimeout(850);await p.evaluate(room=>{document.getElementById('sRoom').value=room;document.getElementById('syncSave').click();},z);await p.waitForFunction(room=>window.__dbg.cfg()?.room===room&&window.__dbg.cfg()?.baseRev>0&&!window.__dbg.cfg()?.dirty,z,{timeout:15000});const remote=await row(z);assert.equal(remote.state.events[0].note,'NEW_ROOM');result.roomSwitchContinuesFirstPush=true;await fetch(MOCK+'/__delay?ms=0');await c.close();}
 assert.equal(external,0);
}finally{await fetch(MOCK+'/__delay?ms=0').catch(()=>{});console.log(JSON.stringify({...result,externalRequests:external},null,2));await b.close();}
