import {createRequire}from'node:module';
import assert from'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_NODE_MODULES?process.env.CODEX_NODE_MODULES+'/playwright':'playwright');
const b=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM});
const result={};let external=0;
const state=(profile={})=>({events:[],axes:{},inbox:[],dismissed:[],archived:{},qualifications:[],outProposals:[],ignoredOut:{},radarSeen:{},radarIdentity:{},seedVersion:2,resultVersion:1,updatedAt:1,profile:{done:true,pdb:false,name:'v8117 격리',jobs:['연구'],axisOrder:[],criteria:{},excludeCompanies:[],excludeRoles:[],strength:'',want:'',avoid:'',prompt:'',createdAt:1,...profile}});
const item=(key='v1',deadline='2026-09-30',active=true,company='격리 연구소',role='연구개발')=>({feed_key:key,company,role,deadline,official_url:'https://example.test/job',payload:{company,role,url:'https://example.test/job',schedule:[{stage:'apply',date:deadline,time:'17:00'}]},published_at:new Date().toISOString(),active});
const ok=()=>[{status:'ok',completed_at:new Date().toISOString(),candidate_count:1,checked_company_count:50}];
async function open(seed,items=[item()],status=ok()){
 const c=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),fx={items,status};
 await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='cdn.jsdelivr.net')return r.fulfill({status:200,contentType:'text/css',body:''});if(u.hostname!=='127.0.0.1'||!['8877','8878','8899'].includes(u.port)){external++;return r.abort('blockedbyclient');}if(u.port==='8878')return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(u.pathname.includes('items')?fx.items:fx.status)});return r.continue();});
 if(seed)await c.addInitScript(seed=>localStorage.setItem('jobRadarStateV3',JSON.stringify(seed)),seed);
 const p=await c.newPage();p.setDefaultTimeout(8000);await p.goto('http://127.0.0.1:8899/',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>!!window.__dbg);return{c,p,fx};
}
const snap=p=>p.evaluate(()=>{const s=window.__dbg.state();return{inbox:s.inbox,events:s.events,meta:s.radarMeta,maps:[!!s.radarSeen,!!s.radarIdentity],status:document.getElementById('radarStatus').textContent};});
const refresh=async p=>{await p.evaluate(()=>window.dispatchEvent(new Event('online')));await p.waitForTimeout(400);};
try{
 {const{c,p}=await open();await p.click('#obNext');await p.fill('#i_name','신규 연구 사용자');await p.click('#obNext');await p.click('[data-job="R&D·연구개발"]');for(let i=0;i<6;i++)await p.click('#obNext');await p.waitForFunction(()=>window.__dbg.state().radarMeta?.feedStatus==='ok');const x=await snap(p);assert.equal(x.inbox.length,1);assert.deepEqual(x.maps,[true,true]);result.freshOnboardingFirstFeed=true;await c.close();}
 {const{c,p}=await open(state({jobs:['영업관리'],excludeCompanies:['제외 회사'],excludeRoles:['OFC']}),[item('excluded','2026-09-30',true,'제외 회사','영업관리 OFC')]);await p.waitForFunction(()=>window.__dbg.state().radarMeta?.feedStatus);assert.equal((await snap(p)).inbox.length,0);result.personalExclusions=true;await c.close();}
 {const{c,p,fx}=await open(state());await p.waitForFunction(()=>window.__dbg.state().inbox.length===1);await p.click('.tab[data-tab="inbox"]');await p.click('[data-drop]');fx.items=[item('v2')];await refresh(p);assert.equal((await snap(p)).inbox.length,0);result.dismissedUpdateStaysDismissed=true;await c.close();}
 {const{c,p,fx}=await open(state());await p.waitForFunction(()=>window.__dbg.state().inbox.length===1);fx.items=[item('v2','2026-10-05')];await refresh(p);let x=await snap(p);assert.equal(x.inbox.length,1);assert.equal(x.inbox[0].schedule[0].date,'2026-10-05');await p.click('.tab[data-tab="inbox"]');await p.click('[data-accept]');x=await snap(p);assert.equal(x.events.length,1);assert.equal(x.events[0].date,'2026-10-05');fx.items=[item('v3','2026-10-10')];await refresh(p);await p.click('.tab[data-tab="inbox"]');await p.click('[data-accept]');x=await snap(p);assert.equal(x.events.length,1);assert.equal(x.events[0].date,'2026-10-10');result.updateCandidateReplacesAndUpdates=true;await c.close();}
 {const{c,p,fx}=await open(state());await p.waitForFunction(()=>window.__dbg.state().inbox.length===1);fx.items=[item('v1','2026-09-30',false)];await refresh(p);assert.equal((await snap(p)).inbox.length,0);result.inactiveRemoved=true;await c.close();}
 {const{c,p}=await open(state(),[item('past','2026-09-15')]);await p.waitForFunction(()=>window.__dbg.state().radarMeta?.feedStatus);assert.equal((await snap(p)).inbox.length,0);result.pastDeadlineSuppressed=true;await c.close();}
 {const{c,p}=await open(state(),[item()],[{status:'ok',completed_at:'2026-09-01T00:00:00Z',candidate_count:1,checked_company_count:50}]);await p.waitForFunction(()=>window.__dbg.state().radarMeta?.feedStatus);assert.match((await snap(p)).status,/업데이트 필요/);result.staleNotLatest=true;await c.close();}
 {const{c,p}=await open(state(),[],[]);await p.waitForFunction(()=>window.__dbg.state().radarMeta?.feedStatus);const x=await snap(p);assert.equal(x.meta.feedStatus,'unknown');assert.match(x.status,/상태 확인 필요/);result.missingStatusUnknown=true;await c.close();}
 {const s=state();s.events=[{id:'a',company:'검수A',role:'전략기획',tier:'A',date:'2026-09-30',time:'17:00',stage:'apply',kind:'deadline',result:'pass',hold:false,note:'메모',url:''},{id:'b',company:'검수A',role:'전략기획',tier:'A',date:'2026-10-05',time:'',stage:'test',kind:'process',result:'',hold:false,note:'메모2',url:''},{id:'c',company:'검수B',role:'전략기획',tier:'A',date:'2026-10-10',time:'',stage:'apply',kind:'deadline',result:'',hold:false,note:'',url:''}];s.archived['검수A|전략기획']={at:1};s.ignoredOut['검수A|전략기획']={basis:'x'};s.outProposals=[{key:'검수A|전략기획',company:'검수A',role:'전략기획'}];const{c,p}=await open(s,[]);await p.waitForFunction(()=>window.__dbg.state().radarMeta?.feedStatus);await p.click('.tab[data-tab="apps"]');await p.click('[data-pc="종료"]');await p.click('[data-open="검수A|전략기획"]');await p.click('#apEdit');assert.deepEqual(await p.evaluate(()=>[...document.querySelectorAll('.scrim.open')].map(x=>x.id)),['edBg']);await p.fill('#edCompany','검수A수정');await p.fill('#edRole','사업기획');await p.click('#edSave');const renamed=await p.evaluate(()=>{const s=window.__dbg.state(),k='검수A수정|사업기획';return{count:s.events.filter(x=>x.company==='검수A수정'&&x.role==='사업기획').length,arch:!!s.archived[k],ign:!!s.ignoredOut[k],proposal:s.outProposals[0].key,old:!!s.archived['검수A|전략기획'],result:s.events.find(x=>x.id==='a').result,note:s.events.find(x=>x.id==='a').note};});assert.deepEqual(renamed,{count:2,arch:true,ign:true,proposal:'검수A수정|사업기획',old:false,result:'pass',note:'메모'});await p.click('#apEdit');await p.fill('#edCompany','검수B');await p.fill('#edRole','전략기획');const before=await p.evaluate(()=>JSON.stringify(window.__dbg.state()));await p.click('#edSave');assert.equal(await p.evaluate(()=>JSON.stringify(window.__dbg.state())),before);assert.equal(await p.locator('#edWarn').isVisible(),true);await p.click('#edCancel');await p.click('#apClose');await p.click('[data-pc=""]');await p.click('[data-open="검수B|전략기획"]');assert.equal(await p.textContent('#apArchive'),'지원 안 함');await p.click('[data-edit]');assert.deepEqual(await p.evaluate(()=>[document.getElementById('fcompany').readOnly,document.getElementById('frole').readOnly]),[true,true]);result.renameReferencesCollisionAndReadonly=true;await c.close();}
 assert.equal(external,0);
}finally{console.log(JSON.stringify({...result,externalRequests:external},null,2));await b.close();}
